name: CI/CD

# How to
# Run `firebase login:ci` Then copy your token.
# Open GitHub repository and go to Settings, then Secrets. Add your secret and name it FIREBASE_TOKEN.

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch.
on:
  push:
    branches:
      - master
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          yarn --pure-lockfile
          yarn build

      - name: Create Service Account and ENV
        run: |
          echo $SERVICE_ACCOUNT > ./dist/serviceAccountKey.json
          cat ./dist/serviceAccountKey.json
          cp ./env.json.development ./env.json
        shell: bash
        env:
          SERVICE_ACCOUNT: ${{secrets.SERVICE_ACCOUNT}}

      - name: Activate Development Project
        uses: w9jds/firebase-action@master
        with:
          args: use develop
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Set ENV
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set env=\"$(cat env.json)\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }} --force --project develop
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          yarn --pure-lockfile
          yarn build

      - name: Create Service Account and ENV
        run: |
          echo $SERVICE_ACCOUNT_PROD > ./dist/serviceAccountKey.json
          cat ./dist/serviceAccountKey.json
          cp ./env.json.production ./env.json
          rm -rf .git .github
        shell: bash
        env:
          SERVICE_ACCOUNT_PROD: ${{secrets.SERVICE_ACCOUNT_PROD}}

      - name: Activate Production Project
        uses: w9jds/firebase-action@master
        with:
          args: use production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}

      - name: Set ENV
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set env=\"$(cat env.json)\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}

      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --token ${{ secrets.FIREBASE_TOKEN_PROD }} --force --project production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
